module.exports = [
  {
    id: 'ey327243hfsdke23',
    created: '22 Agt 2020 10:21',
    lastActive: '23 Des 2020 09:21',
    location: 'Chicago, Illinois, US',
    photoProfile:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?crop=entropy&cs=srgb&fm=jpg&ixid=Mnw3MjAxN3wwfDF8c2VhcmNofDJ8fHBvcnRyYWl0fGVufDB8fHx8MTYzNjU1Njg4NQ&ixlib=rb-1.2.1&q=85&q=85&fmt=jpg&crop=entropy&cs=tinysrgb&w=450',
    owner: 'Samanta William',
    userName: 'samanta12',
    mobileNumber: '+628131723721',
    email: 'deb.bake@example.com',
    dob: '01/01/1999',
    likeCount: '536',
    commentCount: '4',
    repostCount: '12',
    status: 'Flag',
    interest: ['Makan', 'Minum'],
  },
  {
    location: 'Bangalore, Karnataka, India',
    timestamp: '22 Agt 2020 10:21',
    owner: 'Rajoo Samanta',
    userName: 'rajoo12',
    email: 'deb.bake@example.com',
    likeCount: '536',
    commentCount: '4',
    repostCount: '12',
    status: 'Active',
  },
  {
    location: 'Chennai, India',
    timestamp: '21 Sept 2020 14:42',
    owner: 'Taphasya Dalang',
    userName: 'tapasya12',
    email: 'deb.bake@example.com',
    likeCount: '536',
    commentCount: '4',
    repostCount: '12',
    status: 'Take Down',
  },
  {
    location: 'Chennai, India',
    timestamp: '21 Sept 2020 14:42',
    owner: 'Taphasya Dalang',
    email: 'deb.bake@example.com',
    likeCount: '536',
    commentCount: '4',
    repostCount: '12',
    status: 'Banned',
  },
];
